version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: patchwork
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - assets/patchwork.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'

release:
  github:
    owner: tionis
    name: patchwork
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Patchwork {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release!

  footer: |
    ## Docker Images
    
    Docker images are available at:
    - `ghcr.io/tionis/patchwork:{{ .Tag }}`
    - `ghcr.io/tionis/patchwork:latest`
    
    ## Installation
    
    ### Binary Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### Docker
    
    ```bash
    docker run -p 8080:8080 ghcr.io/tionis/patchwork:{{ .Tag }}
    ```
    
    ### From Source
    
    ```bash
    go install github.com/tionis/patchwork@{{ .Tag }}
    ```

dockers:
  - image_templates:
      - "ghcr.io/tionis/patchwork:{{ .Tag }}"
      - "ghcr.io/tionis/patchwork:v{{ .Major }}"
      - "ghcr.io/tionis/patchwork:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/tionis/patchwork:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=A simple communication backend for scripts and other small applications
      - --label=org.opencontainers.image.url=https://github.com/tionis/patchwork
      - --label=org.opencontainers.image.source=https://github.com/tionis/patchwork
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
