FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY patchwork /patchwork
COPY assets /assets

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD ["/patchwork", "healthcheck", "--url", "http://localhost:8080/healthz"]

USER nonroot:nonroot

ENV LOG_LEVEL=info
ENTRYPOINT ["/patchwork", "start"]
